name: CobbleOreGen
version: 1.1.0
main: com.trytig.cobbleoregen.CobbleOreGen
api-version: 1.16
commands:
  cobbleoregen:
    description: CobbleOreGen Command
    aliases:
      - cog
permissions:
  cobbleoregen.reload:
    description: Reloads the plugin
    default: op
  cobbleoregen.*:
    description: All permissions
    default: op
    children:
      cobbleoregen.reload: true